from distutils.core import setup

setup(name='posterior',
    version='0.1',
    description="Pacman repository, package and PKGBUILD library",
    author="H W Tovetjärn",
    author_email="totte@tott.es",
    url="http://www.github.com/totte/posterior",
    py_modules=['posterior'],
    classifiers=['Development Status :: 2 - Pre-Alpha',
        'Intended Audience :: Developers',
        'License :: OSI Approved :: MIT License',
        'Operating System :: OS Independent',
        'Programming Language :: Python',
        'Programming Language :: Python :: 3',
        'Programming Language :: Python :: 3.2',
        'Programming Language :: Python :: 3.3',
        'Topic :: Software Development :: Interpreters',
    ],
)
